{{- if .Values.nginx.sites.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.sites.configMapName }}
data:
  {{- range $k, $v := .Values.nginx.sites.servers }}
  {{ $k }}.conf: |
    upstream {{ $k }} {
      ip_hash;
      server {{ $v.destination.host }}:{{ $v.destination.port }};
    }
    server {
      listen 80;
      server_name {{ $v.listen.host }};
      location / {
        proxy_pass       {{ $v.destination.protocol }}://{{ $k }};
        {{ toYaml $v.parameters | indent 6 | trim | trimPrefix "|" }}
      }
    }
  {{- end }}
{{- end }}
