apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.sites.configMapName }}
data:
  proxy-one.conf: |
    server {
      listen 80;
      server_name one.example.com;
      location / {
        proxy_pass       http://client-one:80;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        add_header       X-Upstream      $upstream_addr;
      }
    }
  proxy-two.conf: |
    server {
      listen 80;
      server_name two.example.com;
      location / {
        proxy_pass       http://client-two:80;
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        add_header       X-Upstream      $upstream_addr;
      }
    }
