name: Run tests for feature

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:

jobs:
  test-docker:
    name: Run tests in docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build images
        working-directory: ./test/docker
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run docker tests
        working-directory: ./test/docker
        run: |
          ../helpers/bats/bin/bats test.bats --print-output-on-failure

  test-kubernetes:
    name: Run tests in kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install KinD Kubernetes
        uses: helm/kind-action@v1.7.0
        with:
          install_only: true

      - uses: zufardhiyaulhaq/setup-istioctl@v1.1.0
        with:
          version: 1.17.2

      - name: Run kubernetes tests
        working-directory: ./test/kubernetes
        run: |
          ../helpers/bats/bin/bats test.bats --print-output-on-failure
