name: main

on:
  push:
    branches:
      - main

jobs:
  test-docker:
    name: Run tests in docker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run docker tests
        working-directory: ./test/docker
        run: |
          ./helpers/bats/bin/bats install.bats

  test-kubernetes:
    name: Run tests in kubernetes

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build images
        working-directory: ./test
        run: |
          docker compose -f docker-compose.yaml build

      - name: Run docker tests
        working-directory: ./test/docker
        run: |
          ./helpers/bats/bin/bats install.bats

  docker:
    name: Build and push image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-scripts
        uses: docker/metadata-action@v4
        with:
          images: jakoberpf/zerotier-gateway

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jakoberpf/zerotier-gateway

      - name: Build image and push to Docker Hub tagged with latest
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jakoberpf/zerotier-gateway:latest
          labels: ${{ steps.meta.outputs.labels }}
