name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release-chart:
    name: Release chart to github pages and container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Release chart to Github Pages
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true
          
      # - name: Push Charts to Container Registry
      #   working-directory: charts
      #   run: |
      #     REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
      #     for CHART_DIR in $(ls -d */Chart.yaml | cut -d '/' -f 1); do
      #       CHART_NAME="$(yq '.name' ${CHART_DIR}/Chart.yaml)"
      #       echo "Packaging ${CHART_NAME} chart"
      #       helm dependency build ${CHART_DIR}
      #       helm package ${CHART_DIR}
      #       PKG_NAME=`ls *.tgz`
      #       echo "Pushing ${CHART_NAME} chart"
      #       helm push ${PKG_NAME} oci://ghcr.io/${REPO_OWNER}/charts
      #       rm ${PKG_NAME}
      #     done
